version: '3.8'

services:
  rse-server:
    build: .
    depends_on:
      - database
    environment:
      DATABASE_URL: "postgres://postgres:password@database:5432/rse"
      DISCORD_TOKEN: ${DISCORD_TOKEN}
  database:
    image: postgres:17.6-trixie
    restart: always
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rse
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
